// Canonical currency catalog. IDs are lowercase because every rates table and
// persisted preference uses them as stable keys; localized names live in i18n.
export const ANCHOR_CURRENCY = "usd";
export const MIN_VISIBLE_CURRENCIES = 2;
export const DEFAULT_FAVORITES = Object.freeze(["usd", "eur", "rub", "btc", "eth"]);

export const CURRENCIES = Object.freeze([
  // Fiat currencies
  { id: "usd", name: "Доллар США", symbol: "$", flag: "🇺🇸", type: "fiat", visible: true },
  { id: "eur", name: "Евро", symbol: "€", flag: "🇪🇺", type: "fiat", visible: true },
  { id: "rub", name: "Российский рубль", symbol: "₽", flag: "🇷🇺", type: "fiat", visible: true },
  { id: "uah", name: "Украинская гривна", symbol: "₴", flag: "🇺🇦", type: "fiat", visible: true },
  { id: "kzt", name: "Казахстанский тенге", symbol: "₸", flag: "🇰🇿", type: "fiat", visible: true },
  { id: "gbp", name: "Британский фунт", symbol: "£", flag: "🇬🇧", type: "fiat", visible: true },
  { id: "cny", name: "Китайский юань", symbol: "¥", flag: "🇨🇳", type: "fiat", visible: true },
  { id: "try", name: "Турецкая лира", symbol: "₺", flag: "🇹🇷", type: "fiat", visible: true },
  { id: "jpy", name: "Японская иена", symbol: "¥", flag: "🇯🇵", type: "fiat", visible: true },
  { id: "chf", name: "Швейцарский франк", symbol: "Fr", flag: "🇨🇭", type: "fiat", visible: true },
  { id: "sek", name: "Шведская крона", symbol: "kr", flag: "🇸🇪", type: "fiat", visible: true },
  { id: "aud", name: "Австралийский доллар", symbol: "A$", flag: "🇦🇺", type: "fiat", visible: true },
  { id: "cad", name: "Канадский доллар", symbol: "C$", flag: "🇨🇦", type: "fiat", visible: true },
  { id: "nok", name: "Норвежская крона", symbol: "kr", flag: "🇳🇴", type: "fiat", visible: true },
  { id: "dkk", name: "Датская крона", symbol: "kr", flag: "🇩🇰", type: "fiat", visible: true },
  { id: "pln", name: "Польский злотый", symbol: "zł", flag: "🇵🇱", type: "fiat", visible: true },
  { id: "czk", name: "Чешская крона", symbol: "Kč", flag: "🇨🇿", type: "fiat", visible: true },
  { id: "gel", name: "Грузинский лари", symbol: "₾", flag: "🇬🇪", type: "fiat", visible: true },
  { id: "amd", name: "Армянский драм", symbol: "֏", flag: "🇦🇲", type: "fiat", visible: true },
  { id: "azn", name: "Азербайджанский манат", symbol: "₼", flag: "🇦🇿", type: "fiat", visible: true },
  { id: "uzs", name: "Узбекский сум", symbol: "soʻm", flag: "🇺🇿", type: "fiat", visible: true },
  { id: "inr", name: "Индийская рупия", symbol: "₹", flag: "🇮🇳", type: "fiat", visible: true },
  { id: "krw", name: "Южнокорейская вона", symbol: "₩", flag: "🇰🇷", type: "fiat", visible: true },
  { id: "aed", name: "Дирхам ОАЭ", symbol: "د.إ", flag: "🇦🇪", type: "fiat", visible: true },
  { id: "ils", name: "Израильский шекель", symbol: "₪", flag: "🇮🇱", type: "fiat", visible: true },
  { id: "brl", name: "Бразильский реал", symbol: "R$", flag: "🇧🇷", type: "fiat", visible: true },
  { id: "mxn", name: "Мексиканское песо", symbol: "Mex$", flag: "🇲🇽", type: "fiat", visible: true },
  { id: "zar", name: "Южноафриканский рэнд", symbol: "R", flag: "🇿🇦", type: "fiat", visible: true },
  { id: "nzd", name: "Новозеландский доллар", symbol: "NZ$", flag: "🇳🇿", type: "fiat", visible: false },
  { id: "huf", name: "Венгерский форинт", symbol: "Ft", flag: "🇭🇺", type: "fiat", visible: false },
  { id: "ron", name: "Румынский лей", symbol: "lei", flag: "🇷🇴", type: "fiat", visible: false },
  { id: "bgn", name: "Болгарский лев", symbol: "лв", flag: "🇧🇬", type: "fiat", visible: false },
  { id: "hkd", name: "Гонконгский доллар", symbol: "HK$", flag: "🇭🇰", type: "fiat", visible: false },
  { id: "sgd", name: "Сингапурский доллар", symbol: "S$", flag: "🇸🇬", type: "fiat", visible: false },
  { id: "thb", name: "Тайский бат", symbol: "฿", flag: "🇹🇭", type: "fiat", visible: false },
  { id: "vnd", name: "Вьетнамский донг", symbol: "₫", flag: "🇻🇳", type: "fiat", visible: false },
  { id: "idr", name: "Индонезийская рупия", symbol: "Rp", flag: "🇮🇩", type: "fiat", visible: false },
  { id: "myr", name: "Малайзийский ринггит", symbol: "RM", flag: "🇲🇾", type: "fiat", visible: false },
  { id: "php", name: "Филиппинское песо", symbol: "₱", flag: "🇵🇭", type: "fiat", visible: false },
  { id: "sar", name: "Саудовский риял", symbol: "﷼", flag: "🇸🇦", type: "fiat", visible: false },
  { id: "qar", name: "Катарский риял", symbol: "﷼", flag: "🇶🇦", type: "fiat", visible: false },
  { id: "kwd", name: "Кувейтский динар", symbol: "د.ك", flag: "🇰🇼", type: "fiat", visible: false },
  { id: "ars", name: "Аргентинское песо", symbol: "$", flag: "🇦🇷", type: "fiat", visible: false },
  { id: "clp", name: "Чилийское песо", symbol: "$", flag: "🇨🇱", type: "fiat", visible: false },
  { id: "cop", name: "Колумбийское песо", symbol: "$", flag: "🇨🇴", type: "fiat", visible: false },
  { id: "pen", name: "Перуанский соль", symbol: "S/", flag: "🇵🇪", type: "fiat", visible: false },
  { id: "egp", name: "Египетский фунт", symbol: "E£", flag: "🇪🇬", type: "fiat", visible: false },
  { id: "ngn", name: "Нигерийская найра", symbol: "₦", flag: "🇳🇬", type: "fiat", visible: false },
  { id: "mad", name: "Марокканский дирхам", symbol: "د.م.", flag: "🇲🇦", type: "fiat", visible: false },
  { id: "mdl", name: "Молдавский лей", symbol: "L", flag: "🇲🇩", type: "fiat", visible: false },
  { id: "rsd", name: "Сербский динар", symbol: "дин", flag: "🇷🇸", type: "fiat", visible: false },
  { id: "bam", name: "Конвертируемая марка", symbol: "KM", flag: "🇧🇦", type: "fiat", visible: false },
  { id: "isk", name: "Исландская крона", symbol: "kr", flag: "🇮🇸", type: "fiat", visible: false },
  { id: "tjs", name: "Таджикский сомони", symbol: "ЅМ", flag: "🇹🇯", type: "fiat", visible: false },
  { id: "kgs", name: "Киргизский сом", symbol: "сом", flag: "🇰🇬", type: "fiat", visible: false },
  { id: "all", name: "Албанский лек", symbol: "L", flag: "🇦🇱", type: "fiat", visible: false },
  { id: "mkd", name: "Македонский денар", symbol: "ден", flag: "🇲🇰", type: "fiat", visible: false },

  // Cryptocurrencies and tokens
  { id: "btc", name: "Bitcoin", symbol: "₿", flag: "₿", type: "crypto", visible: true },
  { id: "eth", name: "Ethereum", symbol: "Ξ", flag: "Ξ", type: "crypto", visible: true },
  { id: "usdt", name: "Tether", symbol: "₮", flag: "₮", type: "crypto", visible: true },
  { id: "usdc", name: "USD Coin", symbol: "USDC", flag: "USDC", type: "crypto", visible: true },
  { id: "sol", name: "Solana", symbol: "SOL", flag: "SOL", type: "crypto", visible: true },
  { id: "ltc", name: "Litecoin", symbol: "Ł", flag: "Ł", type: "crypto", visible: true },
  { id: "trx", name: "TRON", symbol: "TRX", flag: "TRX", type: "crypto", visible: true },
  { id: "ton", name: "Toncoin", symbol: "TON", flag: "TON", type: "crypto", visible: false },
  { id: "ada", name: "Cardano", symbol: "₳", flag: "₳", type: "crypto", visible: true },
  { id: "near", name: "NEAR Protocol", symbol: "NEAR", flag: "NEAR", type: "crypto", visible: true },
  { id: "okb", name: "OKB", symbol: "OKB", flag: "OKB", type: "crypto", visible: true },
  { id: "sui", name: "Sui", symbol: "SUI", flag: "SUI", type: "crypto", visible: true },
  { id: "xmr", name: "Monero", symbol: "ɱ", flag: "ɱ", type: "crypto", visible: true },
  { id: "dot", name: "Polkadot", symbol: "DOT", flag: "DOT", type: "crypto", visible: true },
  { id: "bnb", name: "BNB", symbol: "BNB", flag: "BNB", type: "crypto", visible: true },
  { id: "xrp", name: "XRP", symbol: "XRP", flag: "XRP", type: "crypto", visible: true },
  { id: "doge", name: "Dogecoin", symbol: "Ð", flag: "Ð", type: "crypto", visible: true },
  { id: "avax", name: "Avalanche", symbol: "AVAX", flag: "AVAX", type: "crypto", visible: true },
  { id: "link", name: "Chainlink", symbol: "LINK", flag: "LINK", type: "crypto", visible: true },
  { id: "atom", name: "Cosmos", symbol: "ATOM", flag: "ATOM", type: "crypto", visible: true },
  { id: "arb", name: "Arbitrum", symbol: "ARB", flag: "ARB", type: "crypto", visible: true },
  { id: "shib", name: "Shiba Inu", symbol: "SHIB", flag: "SHIB", type: "crypto", visible: true },
  { id: "dai", name: "Dai", symbol: "DAI", flag: "DAI", type: "crypto", visible: true },
  { id: "uni", name: "Uniswap", symbol: "UNI", flag: "UNI", type: "crypto", visible: true },
  { id: "bch", name: "Bitcoin Cash", symbol: "BCH", flag: "BCH", type: "crypto", visible: false },
  { id: "algo", name: "Algorand", symbol: "ALGO", flag: "ALGO", type: "crypto", visible: false },
  { id: "apt", name: "Aptos", symbol: "APT", flag: "APT", type: "crypto", visible: false },
  { id: "op", name: "Optimism", symbol: "OP", flag: "OP", type: "crypto", visible: false },
  { id: "fil", name: "Filecoin", symbol: "FIL", flag: "FIL", type: "crypto", visible: false },
  { id: "icp", name: "Internet Computer", symbol: "ICP", flag: "ICP", type: "crypto", visible: false },
  { id: "etc", name: "Ethereum Classic", symbol: "ETC", flag: "ETC", type: "crypto", visible: false },
  { id: "xlm", name: "Stellar", symbol: "XLM", flag: "XLM", type: "crypto", visible: false },
  { id: "xtz", name: "Tezos", symbol: "XTZ", flag: "XTZ", type: "crypto", visible: false },
  { id: "zec", name: "Zcash", symbol: "ZEC", flag: "ZEC", type: "crypto", visible: false },
  { id: "inj", name: "Injective", symbol: "INJ", flag: "INJ", type: "crypto", visible: false },
  { id: "imx", name: "Immutable", symbol: "IMX", flag: "IMX", type: "crypto", visible: false },
  { id: "ldo", name: "Lido DAO", symbol: "LDO", flag: "LDO", type: "crypto", visible: false },
  { id: "rune", name: "THORChain", symbol: "RUNE", flag: "RUNE", type: "crypto", visible: false },
  { id: "aave", name: "Aave", symbol: "AAVE", flag: "AAVE", type: "crypto", visible: false },
  { id: "mkr", name: "Maker", symbol: "MKR", flag: "MKR", type: "crypto", visible: false },
  { id: "pepe", name: "Pepe", symbol: "PEPE", flag: "PEPE", type: "crypto", visible: false },
  { id: "hbar", name: "Hedera", symbol: "HBAR", flag: "HBAR", type: "crypto", visible: false },
  { id: "kas", name: "Kaspa", symbol: "KAS", flag: "KAS", type: "crypto", visible: false },
  { id: "stx", name: "Stacks", symbol: "STX", flag: "STX", type: "crypto", visible: false },
  { id: "grt", name: "The Graph", symbol: "GRT", flag: "GRT", type: "crypto", visible: false },
  { id: "mana", name: "Decentraland", symbol: "MANA", flag: "MANA", type: "crypto", visible: false },
  { id: "sand", name: "The Sandbox", symbol: "SAND", flag: "SAND", type: "crypto", visible: false },
  { id: "gala", name: "Gala", symbol: "GALA", flag: "GALA", type: "crypto", visible: false },
  { id: "flow", name: "Flow", symbol: "FLOW", flag: "FLOW", type: "crypto", visible: false },
  { id: "eos", name: "EOS", symbol: "EOS", flag: "EOS", type: "crypto", visible: false },
  { id: "neo", name: "NEO", symbol: "NEO", flag: "NEO", type: "crypto", visible: false },
  { id: "dash", name: "Dash", symbol: "DASH", flag: "DASH", type: "crypto", visible: false },
  { id: "vet", name: "VeChain", symbol: "VET", flag: "VET", type: "crypto", visible: false },
  { id: "cro", name: "Cronos", symbol: "CRO", flag: "CRO", type: "crypto", visible: false },
  { id: "rpl", name: "Rocket Pool", symbol: "RPL", flag: "RPL", type: "crypto", visible: false },
  { id: "twt", name: "Trust Wallet Token", symbol: "TWT", flag: "TWT", type: "crypto", visible: false },
  { id: "xch", name: "Chia", symbol: "XCH", flag: "XCH", type: "crypto", visible: false },
  { id: "paxg", name: "PAX Gold", symbol: "PAXG", flag: "PAXG", type: "crypto", visible: false },
  { id: "xaut", name: "Tether Gold", symbol: "XAUT", flag: "XAUT", type: "crypto", visible: false }
]);

export const CURRENCY_ALIASES = Object.freeze({
  usd: ["доллар", "доллары", "бакс", "dollar", "dollars", "us dollar", "usdollar", "dollar usa", "美元", "美金"],
  eur: ["евро", "euro", "euros", "欧元"],
  rub: ["руб", "рубль", "рубли", "рублей", "ruble", "rouble", "rubles", "roubles", "rubel", "russischer rubel", "卢布", "俄罗斯卢布"],
  cny: ["юань", "юани", "юаней", "yuan", "renminbi", "rmb", "chinese yuan", "chinesischer yuan", "人民币", "元", "中国元"],
  try: ["лира", "лиры", "турецкая лира", "lira", "turkish lira", "türkische lira", "里拉", "土耳其里拉"],
  uah: ["гривна", "гривны", "hryvnia", "ukrainian hryvnia", "griwna", "格里夫纳"],
  kzt: ["тенге", "tenge", "tengue", "坚戈"],
  gbp: ["фунт", "британский фунт", "pound", "pound sterling", "sterling", "pfund", "英镑"],
  jpy: ["иена", "йена", "yen", "japanischer yen", "日元"],
  chf: ["франк", "швейцарский франк", "swiss franc", "schweizer franken", "瑞士法郎"],
  btc: ["биткоин", "биткойн", "биток", "bitcoin", "比特币"],
  eth: ["эфир", "эфириум", "ethereum", "ether", "以太坊", "以太币"],
  ton: ["тон", "тонкоин", "toncoin", "ton coin", "telegram coin", "телеграм", "开放网络", "吨币"],
  usdt: ["тезер", "tether", "stablecoin", "стейблкоин", "泰达币"],
  usdc: ["usd coin", "юсд коин", "美元币"],
  sol: ["солана", "solana", "索拉纳"],
  doge: ["догикоин", "догecoin", "dogecoin", "狗狗币"],
  xrp: ["рипл", "ripple", "瑞波币"],
  bnb: ["бинанс", "binance coin", "币安币"]
});

export function getCurrencyAliases(id) {
  return CURRENCY_ALIASES[String(id || "").toLowerCase()] ?? [];
}

const CURRENCY_MAP = new Map(CURRENCIES.map((currency) => [currency.id, currency]));

export function getCurrency(id) {
  return CURRENCY_MAP.get(String(id || "").toLowerCase()) ?? null;
}

export function hasCurrency(id) {
  return CURRENCY_MAP.has(String(id || "").toLowerCase());
}
